enableGlobalCache: true

logFilters:
  - level: discard
    pattern: "*"

nmMode: hardlinks-local

nodeLinker: node-modules

npmScopes:
  dfinity:
    npmRegistryServer: "https://registry.npmjs.org/"
