import React, { useState, useCallback, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { useAnima } from '@/hooks/useAnima';
import { EnhancedImmersiveInterface } from '@/components/chat/EnhancedImmersiveInterface';
import { MatrixLayout } from '@/components/layout/MatrixLayout';
import { EnhancedMediaController } from '@/components/media/EnhancedMediaController';
import { useQuantumPerception } from '@/hooks/useQuantumPerception';
import { useMediaPatternAnalysis } from '@/hooks/useMediaPatternAnalysis';
import { useNeuralNetwork } from '@/hooks/useNeuralNetwork';
import { QuantumField } from '@/components/ui/QuantumField';
import { WaveformGenerator } from '@/components/personality/WaveformGenerator';
import { NeuralPatternVisualizer } from '@/components/neural-link/NeuralPatternVisualizer';
import { useQuantumState } from '@/hooks/useQuantumState';